pipeline {
  agent {
    label "lead-toolchain-skaffold"
  }
  environment {
    SKAFFOLD_DEFAULT_REPO = 'docker.artifactory.liatr.io/liatrio'
  }
  stages {
    stage('Build') {
      steps {
        script {
          container('skaffold') {
            docker.withRegistry("https://${SKAFFOLD_DEFAULT_REPO}", 'jenkins-credential-artifactory') {
              sh "skaffold build -f .cache/skaffold.yaml"
            }
          }
        }
      }
    }
  }
}

